name: 'airlines_project'
version: '1.0.0'
config-version: 2

profile: 'airlines_profile'

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]

models:
  airlines_project:
    +materialized: view
