version: 2

models:
  - name: stg_airlines
    description: "Staging model selecting all columns from airlines_r_raw"
    columns:
      - name: flight_id
        description: "Unique identifier for each flight"
      - name: carrier
        description: "Airline carrier code"
      - name: arr_delay
        description: "Arrival delay in minutes"
      - name: dep_delay
        description: "Departure delay in minutes"
      - name: flight_date
        description: "Date of the flight"

models:
  - name: stg_weather_daily
    description: "Staging model for daily weather data"
  - name: stg_weather_hrly
    description: "Staging model for hourly weather data"