version: 2

models:
  - name: flights_summary
    description: "Summary of flights by carrier from airlines_r_raw"
    columns:
      - name: carrier
        tests:
          - not_null
      - name: total_flights
        tests:
          - not_null
      - name: avg_arrival_delay
        tests:
          - not_null
